require('settings')
require('autocmd')
require('plugins')
require('keymaps')
require('plugins.coc')
require('plugins.theme')
require('plugins.icon') 
require('plugins.tree')
require('plugins.lualine')
require('plugins.comt')
-- require('plugins.luasnip')
require('plugins.bufferline')
require('plugins.treesitter')
require('leap').add_default_mappings()
